services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-nextjs
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
      - MONGODB_URI=${MONGODB_URI}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "3000:3000"
